version: '3.3'
services:

# Tracker Dependency Software
 zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'

# Tracker Dependency Software
 kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "divolte:3:1"
    depends_on:
      - 'zookeeper'
 
 # Tracker 
 divolte:
    build: .
    container_name: divolte
    environment:
      DIVOLTE_KAFKA_TOPIC: "divolte"
      DIVOLTE_KAFKA_CLIENT_ID: "divolte.collector"
      DIVOLTE_KAFKA_BROKER_LIST: "kafka:9093"
      DIVOLTE_COOKIE_DOMAIN: "beautysecrets.ml"
      DIVOLTE_JAVASCRIPT_NAME: "divolte.js"
      DIVOLTE_CONF_DIR: /opt/divolte/divolte-collector/conf
    ports:
      - '8290:8290'
    depends_on:
      - 'kafka'      
 
 # Database
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - cluster.name=RealTimeData
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=nandita
    ulimits:
      memlock:
        soft: -1
        hard: -1  
    ports:
      - '9200:9200'
    volumes:
      - ./database:/usr/share/elasticsearch/data

# Visualisation
 kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    environment:
      SERVER_NAME: clickstreamdatabase
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: nandita
      LOGGING_QUIET: "true"
    restart: always  
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch   
    links:
      - elasticsearch        

volumes:
  kafka_data: {}
  es_data:
    driver: local